<?php
return array(
    'Application',
    'ZF\\DevelopmentMode',
    'ZF\\Apigility',
    'ZF\\Apigility\\Provider',
    'ZF\\Apigility\\Documentation',
    'AssetManager',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'Example'
);